site_name: AI Database MVP
site_description: Multi-agent database AI system for intelligent query generation and execution
site_author: AI Database MVP Team
site_url: https://ai-database-mvp.readthedocs.io

repo_name: ai-database-mvp
repo_url: https://github.com/yourusername/ai-database-mvp
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.insert(0, ".")
          rendering:
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quickstart.md
      - Configuration: getting-started/configuration.md
  - Architecture:
      - Overview: architecture/overview.md
      - Agents: architecture/agents.md
      - Message Bus: architecture/message-bus.md
      - Workflow Engine: architecture/workflow-engine.md
  - API Reference:
      - REST API: api/rest.md
      - WebSocket API: api/websocket.md
      - Python SDK: api/python-sdk.md
  - Development:
      - Coding Standards: CODING_STANDARDS.md
      - Contributing: contributing.md
      - Testing: development/testing.md
      - Debugging: development/debugging.md
  - Deployment:
      - Docker: deployment/docker.md
      - Kubernetes: deployment/kubernetes.md
      - Monitoring: deployment/monitoring.md
  - Examples:
      - Basic Usage: examples/basic.md
      - Advanced Queries: examples/advanced.md
      - Custom Agents: examples/custom-agents.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/ai-database-mvp
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/yourusername/ai-database-mvp

copyright: Copyright &copy; 2024 AI Database MVP Team
